image: python:3.6-alpine
stages:
  - deploy
before_script:
  - pip3 install --upgrade pip3
  - pip3 install setuptools wheel twine

deploy_production:
  stage: deploy
  script:
    - python3 setup.py sdist bdist_wheel
    - twine upload dist/*
  only:
    - tags