image: jjanzic/docker-python3-opencv:latest
stages:
  - deploy
  - test
before_script:
  - apt -y update
  - apt -y install python3-pip
  - pip3 install setuptools wheel twine


test:
  stage: test
  script:
    - pip3 install .
    - python3 test.py