image: ubuntu:bionic
stages:
  - deploy
before_script:
  - apt -y update
  - apt -y install python3-pip
  - pip3 install setuptools wheel twine

deploy_production:
  stage: deploy
  script:
    - python3 setup.py sdist bdist_wheel
    - twine upload dist/*
  only:
    - tags
