site_name: Preimutils
theme:
    name: material
    features:
    - instant
    - tabs
    palette:
      primary: blue grey
      accent: blue grey
markdown_extensions:
  - toc:
      permalink: true
  - codehilite
  - mkautodoc
  - admonition
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
nav : 
    - 'index.md'
    - Installation : installation.md
    - Object Detection Dataset : object-detection.md 
    - Segmentation Dataset: segmentation.md
    - VOC dataset: voc.md
    - COCO dataset: coco.md
